id: P010782
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5063
  title: རྗེ་བཙུན་འཕགས་མ་སྒྲོལ་མའི་རྒྱུད་ཀྱི་བྱུང་བ་དང་བསྟོད་འགྲེལ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  volumes:
    6b6f8ac7458f4c998e9c05990841c198:
      image_group_id: I3CN5065
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
