id: opecha:P010782
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5063
  title: རྗེ་བཙུན་འཕགས་མ་སྒྲོལ་མའི་རྒྱུད་ཀྱི་བྱུང་བ་དང་བསྟོད་འགྲེལ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  volume: ''
  author: ''
