id: IB9DA7110
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T22:19:44+00:00'
last_modified: '2022-06-08T17:29:18.812582+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5063
  title: རྗེ་བཙུན་འཕགས་མ་སྒྲོལ་མའི་རྒྱུད་ཀྱི་བྱུང་བ་དང་བསྟོད་འགྲེལ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC28:
      image_group_id: I3CN5065
      title: ''
      total_pages: 94
      order: 1
      base_file: CC28.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
